### ISSUE TITLE
CKB Open Transaction: An Extensible Transaction Format

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#3608]
## Project Resources

- [Project Introduction and General Discussions](https://github.com/nervosnetwork/ckb/discussions/3607)
    - [All Tagged Discussions](https://github.com/nervosnetwork/ckb/discussions?discussions_q=label%3Af%3Aopen-transaction)
- [Project Management Board](https://github.com/orgs/nervosnetwork/projects/23/views/4)

## Milestones and Deliverables

Start Date: 9/26/2022
- [x] #3639
    - [x] 1 week: User Stories Analysis
- [x] #3640
    - [x] 2 weeks: PoC Requirements Analysis
    - [x] 4 weeks: PoC Development
- [x] CKB Open Transaction Milestone 3: RFCs
    - [x] 4 weeks: RFCs Proposals
- [x] CKB Open Transaction Milestone 4: Alpha
    - [x] 2 weeks: Alpha Requirements Analysis
    - [x] 4 weeks: Alpha Development
        - [x] @doitian RFC for Specification https://github.com/nervosnetwork/rfcs/pull/406
        - [x] @doitian RFC for Use Cases Payments and Swap
        - [x] @EthanYuan Demo for Payments and Swap
- [ ] P2P
    - nervosnetwork/ckb-kanban#21
- [ ] Webapp Demo

## Project Updates

I will lock this issue and post updates here as comments. Please subscribe to this issue and use [this thread](https://github.com/nervosnetwork/ckb/discussions/3607) for discussions.

**Comment by doitian** [comment]
Reserved for future use.

**Comment by doitian** [comment]
Updates:

- I'm still working on the user stories report and will publish an analysis report this week.
- I published a post for open discussions: https://github.com/nervosnetwork/ckb/discussions/3619
- @TheWaWaR will join me to work on the PoC and Alpha.

**Comment by doitian** [comment]
## Weekly Updates on 2022-10-17:

### Last Week

- I have been working on the user stories analysis.
- Got @TheWaWaR and @EthanYuan on board.

### This Week

- Publish the user stories analysis report.
- Brainstorm what to do in the PoC.

### New Discussions

- #3638

**Comment by doitian** [comment]
## Weekly Updates on 2022-10-28

### Last Week
- Research on user stories
    - #3670 
    - #3671 

### Next Week
- Kick-off the PoC development

**Comment by doitian** [comment]
## Weekly Updates on 2023-02-17

### Last Week

- Discuss on the details of the open transaction format.
- Continue writing the RFC draft and demos.

### Next Week

- Continue writing the RFC draft and demos.

**Comment by doitian** [comment]
RFC for the specification is ready for review https://github.com/nervosnetwork/rfcs/pull/406

**Comment by doitian** [comment]
## Updates on 2023-04-13

We are working on the P2P and web app demos.

- We'll implement a public P2P network to exchange open transactions.
- We'll develop demos in https://github.com/EthanYuan/open-transaction-pool as web apps.
