### ISSUE TITLE
todo list of release 0.105.0

### ISSUE THREAD

**Issue by quake** [nervosnetwork/ckb#3630]
- [x] create a PR https://github.com/nervosnetwork/ckb/pull/3631 to merge branch light-client-rebase to develop and code review
- [ ] review 3 rfcs
    - [ ] https://github.com/nervosnetwork/rfcs/pull/349
    - [ ] https://github.com/nervosnetwork/rfcs/pull/370
    - [ ] https://github.com/nervosnetwork/rfcs/pull/375

**Comment by doitian** [comment]
Updated the issue description to make the GitHub link preview work.
