### ISSUE TITLE
CKB Open Transaction Milestone 1: User Stories Analysis

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#3639]
## Infrastructure
- [x] #3638 

## Scenarios
- [x] [RFC39: Cheque Lock](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0039-cheque/0039-cheque.md)
- [x] Swap
- [x] Payment
- [x] Exchange Deposit
- [ ] dApps Deposite: Godwoken, Axon
- [x] Coin Join
- [x] MultiParity Sign
- [x] Crodfunding
- [ ] [CoTA](https://www.cotadev.io/)

## UTXO

- [ ] #3677 

## Reports
- [ ] #3670 
- [ ] #3671

**Comment by xcshuan** [comment]
Maybe OTX can combine with a VM, an additional P2P layer off-chain (which can be a centralized sequencer at the beginning) to collect user transactions and sort transactions, similar to the effect of the account model.
