### ISSUE TITLE
Consensus rule on cellbase outputs maturity period

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#54]
- [x] Propose an RFC for this feature.
- [x] Add a consensus spec configuration `COINBASE_MATURITY`
- [x] Index whether a TX is a cellbase in the chain.
- [x] Cellbase outputs must mature 100 blocks before they can be spent. If a tx uses an output of cellbase in block N, it can only be committed in block M where `M - N >= COINBASE_MATURITY`

**Comment by u2** [comment]
This issue can be assigned to me. :)

**Comment by u2** [comment]
https://github.com/nervosnetwork/ckb/blob/develop/core/src/transaction_meta.rs#L20

In TransactionMeta, we already have a `BitVec` for `output_spent`, there are two options:
1. Add a bool indicating whether it's a cellbase;
2. As https://github.com/paritytech/parity-bitcoin/blob/master/storage/src/transaction_meta.rs#L14, the first bit for the cellbase tx.

**Comment by quake** [comment]
@u2 we will remove `TransactionMeta` in favor of `MMR`, may need alternative solution.

**Comment by u2** [comment]
add on: 

> Make this a configurable option in chain spec.
> Only enable it in testnet chain spec. Disable it in dev and integration.

**Comment by u2** [comment]
#481 I think this issue can be closed.
